/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "oiosaml3-parent"
include(":oiosaml3.java")
include(":oiosaml3-integrationtest")
include(":oiosaml3-demo")
project(":oiosaml3.java").projectDir = file("oiosaml")
project(":oiosaml3-integrationtest").projectDir = file("integrationtest")
project(":oiosaml3-demo").projectDir = file("demo")
