/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.net.sourceforge.htmlunit.htmlunit)
    testImplementation(libs.org.seleniumhq.selenium.selenium.java)
    testImplementation(libs.junit.junit)
}

description = "OIOSAML Integrationtest Java v3"
