/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

val oioSamlMavenRepoUri: String? by rootProject
val oioSamlOpenSamlMavenRepoUri: String? by rootProject

repositories {
    val centralRepo = oioSamlMavenRepoUri
    if(centralRepo != null) {
        maven {
            url = uri(centralRepo)
        }
    } else {
        mavenCentral()
    }

    val oiosamlRepo = oioSamlOpenSamlMavenRepoUri
    if(oiosamlRepo != null) {
        maven {
            name = "shibboleth-releases"
            url = uri(oiosamlRepo)
        }
    }
}

group = "dk.digst"
version = "3.2.2-cap-1"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
