/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.opensaml.opensaml.core.impl)
    api(libs.org.opensaml.opensaml.core.api)
    api(libs.org.opensaml.opensaml.saml.impl)
    api(libs.org.opensaml.opensaml.messaging.impl)
    api(libs.org.opensaml.opensaml.security.api)
    api(libs.org.bouncycastle.bcprov.jdk18on)
    api(libs.org.slf4j.slf4j.api)
    api(libs.jakarta.xml.bind.jakarta.xml.bind.api)
    api(libs.org.glassfish.jaxb.jaxb.runtime)
    api(libs.org.glassfish.jaxb.jaxb.xjc)
    implementation(libs.jakarta.servlet.jakarta.servlet.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.junit.platform.junit.platform.runner)
    testImplementation(libs.org.mock.server.mockserver.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.hsqldb.hsqldb)
    testImplementation(libs.org.slf4j.slf4j.nop)
    testImplementation(libs.org.slf4j.jcl.over.slf4j)
    testImplementation(libs.org.slf4j.log4j.over.slf4j)
}

description = "OIOSAML for Java v3"

val oioSamlMavenReleaseUri: String by rootProject
val oioSamlMavenSnapshotUri: String by rootProject

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
    repositories {
        maven {
            name = "release"
            url = uri(oioSamlMavenReleaseUri)
            isAllowInsecureProtocol = true
            credentials(PasswordCredentials::class.java)
        }
        maven {
            name = "snapshot"
            url = uri(oioSamlMavenSnapshotUri)
            isAllowInsecureProtocol = true
            credentials(PasswordCredentials::class.java)
        }
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.test {
    useJUnitPlatform()
}
